version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.15.3-stretch
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Run tests
          command: echo "This is just sample config, please replace this command with real tests :)"
      - run:
          name: Build and minify app
          command: npm build
  deploy:
    build:
      docker:
        - image: circleci/node:10.15.3-stretch
    steps:
      - checkout
      - run:
          name: Run only into master
          command: echo "Run only into master"
workflows:
  version: 2
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master